import { LATIN_LETTERS } from "../core/constants";
import { LetterTypes, NodeId } from "../core/types";

// =============================================================================
// Reverse Gematria Types
// =============================================================================

export type ReverseGematriaOptions = {
  /** Target individuality (vowels sum) */
  targetVowels?: number;
  /** Target personality (consonants sum) */
  targetConsonants?: number;
  /** Target synthesis (total) */
  targetSynthesis?: number;
  /** Minimum letters (default: 1) */
  minLength?: number;
  /** Maximum letters (default: 8) */
  maxLength?: number;
  /** Maximum results (default: 100) */
  maxResults?: number;
  /** Include digraphs like PH, SH, etc. (default: true) */
  includeDigraphs?: boolean;
};

export type ReverseGematriaResult = {
  letters: string;
  letterDetails: LetterResult[];
  vowelsSum: number;
  consonantsSum: number;
  synthesisSum: number;
};

export type ReverseGematriaOutput = {
  results: ReverseGematriaResult[];
  hasMore: boolean;
  totalFound: number;
};

// =============================================================================
// Existing Types
// =============================================================================

export const DIGRAPHS = new Set<string>([
  LATIN_LETTERS.PH,
  LATIN_LETTERS.TS,
  LATIN_LETTERS.TZ,
  LATIN_LETTERS.SH,
  LATIN_LETTERS.CH,
  LATIN_LETTERS.TH,
  LATIN_LETTERS.KH,
]);

export type LetterResult = {
  latinLetterId: NodeId<LetterTypes.LATIN_LETTER>;
  value: number;
  hebrewLetterId: NodeId<LetterTypes.HEBREW_LETTER>;
  hebrewCharacter: string;
  isVowel: boolean;
}

export type WordResult = {
  letters: LetterResult[];
  vowelsSum: number;
  consonantsSum: number;
  includedGematriaValues: Set<number>;
}

export type GematriaState = {
  includedLetters: LetterResult[];
  vowelsSum: number;
  consonantsSum: number;
  includedGematriaValues: Set<number>;
}

export type LetterPercentages = {
  percentageOfVowels: number;
  percentageOfConsonants: number;
  letters: Record<string, number>;
}

export enum GematriaNumbersWithMeaning {
  One = 1,
  Two = 2,
  Three = 3,
  Four = 4,
  Five = 5,
  Six = 6,
  Seven = 7,
  Eight = 8,
  Nine = 9,
  Eleven = 11,
  TwentyTwo = 22,
  ThirtyThree = 33,
  FortyFour = 44,
}

export const INDIVIDUALITY_NUMBER_MEANINGS: Record<GematriaNumbersWithMeaning, string> = {
  [GematriaNumbersWithMeaning.One]: "The leadership gained in past lives now brings the desire to continue striving for a higher consciousness. This person is independent when it comes to their beliefs. Their longing for free and independent thought remains their deepest inner drive. They should not allow this strong impulse to obstruct the achievement of practical goals in their present life. They will always be aware of their inner strength and find it difficult to accept a secondary position among their peers. If marriage or partnership is involved, they should explore their partner's inner aspirations in order to safeguard a successful relationship. If their individuality becomes too strong, it may manifest as authoritarianism and prove detrimental to their personal happiness. So firm is the intensity of their focus, and so strong the memory of past glory, that they are able to hold to their convictions even when this means breaking off important relationships. Their inner strength gives them something to rely on when situations are tense, and they can be an inspiration to others in difficult times. In terms of individuality, this number is one of the best indications. It denotes a person who is aware of their own importance, yet at the same time appreciates the rights and opinions of others. They ask for other people's point of view, using it as a way to refine their own opinions, which are formed on the basis of genuine knowledge.",
  [GematriaNumbersWithMeaning.Two]: "Strong desire for peace and harmony. They are attentive and diplomatic, adaptable and gentle. They are more of a follower than a leader. Discernment is a strong point of their character; for this reason, they make a good mediator or go-between, helping to bring peace to opposing forces. They avoid hurting other people's feelings, to the point of submitting to their wishes. As a result, they can appear shy and lacking in self-confidence. They should try to overcome indecision, because while they hesitate, others may step forward and claim what should have been theirs. They must encourage themselves to do what they feel is right and not let emotions block their purpose. Their sensitivity can be positive when used to attune to the balancing forces of the universe and to express truths that help everyone gain understanding. As an individuality number, this indicates a person full of tact and diplomacy, non-aggressive, who does not try to impose their opinions, and who listens to other people's ideas before expressing their own.",
  [GematriaNumbersWithMeaning.Three]: "Very conscientious about duty. They understand well the law of the trinity and know that inspiration and imagination bring the best results when used to help others. This can become their life philosophy. They should satisfy their urge to create and to expand activities related to their interests. They seek happiness and find it by making others happy. When someone is depressed, a visit from them brings hope and courage. They should expand their ideals by dedicating themselves to expressing good humor and optimism. They should commit to making their dreams come true, but not to the point where they become impractical. Love is important to them, both in giving and receiving – but they should try to keep a sense of reason in their romantic expansions. They will be happy and well-adjusted when they are bringing happiness to others. As an individuality number, this is one of the best, unless the Personality number is very adverse and prevents these qualities from being expressed. This person has highly developed philosophical and moral qualities and always tries to act for the greater good. Wherever they are, they will exert a strong positive influence, seeking to comfort and brighten the lives of those who are less fortunate. When the Personality is not favorable, the individual may become very selfish, vain, sensual, and concerned only with themselves. This happens especially when the Personality number is 8 or 9. The best combinations for the number 3 occur when the Personality number is 1 or 6, forming a harmonious and powerful nature.",
  [GematriaNumbersWithMeaning.Four]: "Highly organized, a quality that can bring them material success. The practical side permeates their whole being. Others could model themselves on their well-organized life plan. Their loyalty, balance, and reliability mean a great deal to those around them. People know where they stand with them in all things, and feel that any dealings with them will be handled honestly. They approach matters seriously, in business or in love, and for this reason they can make their dreams real in a planned and practical way. As an individuality number, this produces some of the strongest characters, individuals who rise in life through their genius and willpower. They are distinctly optimistic and face obstacles bravely. They do not fear venturing into the unknown. When the Personality allows a suitable individual expression, they can become a true benefactor of humanity. However, if the Personality is expressed by a weak or disharmonic number, they may become overly eccentric and incomprehensible, prone to mental imbalance and the danger of madness. Personality numbers 2 or 9 are the most harmful combinations for a 4 in Individuality.",
  [GematriaNumbersWithMeaning.Five]: "They claim the right to freedom and do not allow any restrictions on their ideals or way of thinking. Variety in self-expression is absolutely essential. They would feel inert and indifferent without the stimulus of change and new perspectives. Travel is one of the desires of their soul, as they see it as educational and as something that broadens their horizons. Pettiness is not tolerated. If they feel themselves slipping into routine, a journey, a new occupation, or a holiday can shift the vibrations for the better and open new paths for continued inner growth. This number is weak as an individuality number, promising little progress in life and favoring mainly the extension of experience, which will be as varied as possible. When the personal character is expressed by a powerful, steady number, the inner struggles and mobility of ideas and feelings do not show much on the surface, and the person can still progress in life and attain a position that matches their talent. However, if the Personality is also weak, the person will drift through life like a butterfly.",
  [GematriaNumbersWithMeaning.Six]: "Strongly responsive to beauty, harmony, and peace. Affectionate, kind, and loyal to those they love. Their mission could be to teach others how to maintain peace and harmony in their lives and to spread the ideal of moral conduct. They work hard to keep domestic harmony through their ideal way of life. Of all the love vibrations of the numbers, this one is the most likely to create a suffocating love, so deep is their desire to live for their immediate family. They must learn to allow family members to express their own desires in life, even when they do not agree with their choices. As an individuality number, it indicates a deeply benevolent and kind nature, but its outer expression depends greatly on the Personality and the Synthesis. This number is strongly limited by prejudices and mistaken ideas, which can expand into malice and even vandalism if it is linked with 8 or 9 in the Personality or in the Synthesis. It easily tends toward extremes, depending on how it combines with the other numbers in the chart.",
  [GematriaNumbersWithMeaning.Seven]: "Calm and reserved, a good thinker, analyst, and mediator. They need a peaceful environment and become irritated in noisy surroundings. Refined, sensitive, withdrawn, and often psychic. They may live alone and remain single, or become celibate and join one of humanity's higher mystical orders. Their true nature is to be calm, to develop depth of character, and thus to benefit humanity through philosophy. As an individuality number, it is very variable in its effects, everything depending on the individual's moral development. When supported by harmonious numbers in the Personality and in the Synthesis, its influence is among the best and most beneficial for humanity, giving rise to great philanthropy.",
  [GematriaNumbersWithMeaning.Eight]: "Ambition is their key word. They believe in achievement and do not let any obstacle stop them from reaching their goals. Their number is not an easy one to handle, but their efforts will be rewarded. They are someone who undertakes great works in order to stand out from the crowd and reach the heights. They have the ability to organize large groups and enterprises successfully. Psychology would help them understand the masses they may work with. Others expect more from them than from the average person, and for this reason they must trust their inner Self to guide them in remaining in a position of leadership. This is the number of high-performance athletes. As an individuality number, this gives one of the strongest and most enterprising characters. The person has great willpower, concentration, and the ability to carry their undertakings through. When they are morally developed, these qualities place them on the highest levels of life.",
  [GematriaNumbersWithMeaning.Nine]: "Intuition is strongly active in their life. They are sensitive, imaginative, and able to think in abstract terms. Though they may sometimes seem vague, they are extremely impressionable, compassionate, and generous. They need both to give and to receive love. They are gentle and merciful, with an expansive consciousness dedicated to the upliftment of humanity. This could be the number of a master or adept from a previous life. The influence of this number in individuality is very strong and can produce remarkable results, both for good and for ill. In a morally developed person, the magnetic power becomes very great, and they possess notable healing abilities. When the Personality is weak, the individual becomes a victim of misfortune and adverse events, through lack of control over their passions.",
  [GematriaNumbersWithMeaning.Eleven]: "Has been on the spiritual path for a long time, probably for more than one incarnation. Through spiritual evolution they have learned many of the mysteries of life and death. They have courage, talent, and leadership ability; they are understanding, wise, intuitive and, often, clairvoyant, with extremely sensitive extrasensory perception and strong spiritual inclinations. They also possess the courage to face many changes and unexpected upheavals.",
  [GematriaNumbersWithMeaning.TwentyTwo]: "With the power of 22, you carry the urge to continue the tangible achievements of past lives. You seek material accomplishment. You are the master builder. Your ambitious soul leaves the world a tangibly better place for your having been here; for this reason, you need to maintain mental balance while expressing your ideals in a practical way.",
  [GematriaNumbersWithMeaning.ThirtyThree]: "You are willing to make sacrifices for humanity. You have a clear vision of future world conditions and feel ready to help in every way you can to bring peace to all humankind. At times, the vibrations of your Life Lesson (birth date) may be at odds with the longings of your soul. In spite of this, you will strive to practice generosity and to consider other people's point of view. This circumstance may temporarily force you into a background position, but it does not destroy your hope of one day holding a place from which you can promote your ideals. You are always ready to help others.",
  [GematriaNumbersWithMeaning.FortyFour]: "Universal concepts are part of your consciousness; they now express themselves as inner impulses to bring about great advances in world culture. Whether by uniting the practical with the global sphere, a governmental chamber or even the UN may offer you the opportunity to promote these ideals among all peoples. You are willing to take on great responsibilities. Your inner Self recognizes that you are an adept; now the challenge is how to manifest this to the outer world. You trust that your soul will guide you toward fields where your great ideals can be advanced. You have an innate ability to solve everyday problems and can work with others to help them organize their lives.",
}

export const PERSONALITY_NUMBER_MEANINGS: Record<GematriaNumbersWithMeaning, string> = {
  [GematriaNumbersWithMeaning.One]: "You present to the world an image of someone independent and capable, the executive type. Others see you as a unique individual, set apart from the ordinary crowd – perhaps something of a loner in some respects, but definitely different. They expect you to be able to take control of any situation and to manage an organization or a club effectively. People look to you to get the job done, because you appear to be the leader, the pioneer, the person with ideas who always knows where to go and what to do. Creating the right image comes first in your mind, and you rely on the strength of your personality, as if it were your identity card, to gain entry into social circles. You may sometimes appear too aggressive or domineering. In that case, the selfish need to assert your individuality is fulfilled at the expense of the free expression of those around you. As a number 1 person, you like to dress to be at the forefront of fashion. You enjoy exclusive styles. On the negative side, you may even dress in an eccentric way, or in a way that goes beyond the boundaries of good taste. As an indicator of Personality, this number is rarely favorable, as it almost always denotes selfishness, disregard for the opinion of others, a tendency to interfere in other people's lives, and a desire to dominate those around. A person under this influence likes to give their opinion without being asked, insists that their method is always the best, and does not respect the feelings of others. Only when it is in perfect harmony with the Individuality number does the number 1 become favorable.",
  [GematriaNumbersWithMeaning.Two]: "You appear calm and modest and seem to need a peaceful environment in which to live. You are demanding about details; neatness and cleanliness are a must. Instead of making a grand entrance, you prefer to stay in the background, working behind the scenes or in cooperation with others. You are attractive and popular with the opposite sex. This is partly due to your desire for companionship and harmony, which makes you tolerant of others. You seem incomplete in yourself. You may appear restless and dissatisfied with circumstances because of the constant weighing and balancing you do in every situation. You may have difficulty making decisions, as both sides often seem very clear to you. At times, you can show bad temper and use sharp words. You dress with care and discretion, preferring a balanced and pleasant appearance. You should choose clothes of a lighter style, reflecting your more passive and artistic nature. As a Personality number, 2 is not very favorable, producing a nervous, irritable, flattering, and scheming disposition. It makes countless promises, but almost never carries them out, always looking for excuses.",
  [GematriaNumbersWithMeaning.Three]: "Extremely charming, pleasant, and sociable. You act in an attractive way, seeking pleasure and joy. Loyalty and honesty strengthen your idealistic nature. Communication is a vital part of your personality, and you find it very easy to express yourself. As an avid conversationalist, you shine in any group. You are like the sun, lighting up the world of those you meet, spreading brightness and optimism wherever you go. Others naturally gather around your warmth. Your outgoing personality can become so large that it leads to your downfall, through prejudice and envy. In such cases, your gift of speech tends to degenerate into gossip, exaggeration, and frivolity. If you are a woman, you may be beautiful and have an attractive body. You will enjoy personal adornments – jewelry, necklaces, makeup – and have an artistic flair for choosing clothes. On the negative side, you may become carelessly dressed, neglecting both style and the way you look after your wardrobe. As a Personality number, 3 gives pleasant manners, a sensitive and compassionate nature, public appeal, and popularity. When Individuality is occupied by a disharmonic number, 3 in Personality produces a demanding, critical person, inclined to arguments, vain, and impatient. Your selfishness will be greatly increased by the presence of 8 or 9 in Individuality, producing someone who will only be useful to themselves.",
  [GematriaNumbersWithMeaning.Four]: "You show the world a determined and well-directed attitude. You appear conservative, self-disciplined, and practical. You dream of an orderly existence through which your skill in both physical and mental application will produce conventional and even useful results. You are the honest, hard-working type, who respects values and effort. You like the land, nature, home, and your country. You may become so disciplined that you have no time for leisure, which can eventually isolate you from others. Extremely careful and frugal, you tend to become defensive and stingy. Roughness and bad temper can drive you even further away from social contact. Or, as a reaction in the opposite direction, you may appear completely undisciplined and lazy. Good sportswear appeals to you because it is durable and needs little care. You choose your work clothes carefully, insist on good quality, and often have them made to measure. You like to appear clean and well-groomed at all times. You are conservative both in the way you dress and in your behavior. Except in cases where Individuality is expressed by a strong and powerful number, such as 1, 3, 4, or 8, this number is harmful on the Personality level. In fact, when Individuality is not strong enough to hold the reins of the fiery vibrational impulses of 4 in Personality, the result is a very impulsive, violent, hasty, and inconstant disposition that can never bring good results in life. Numbers 2 and 5 in Individuality are too weak to contain the vibrations of 4, and 9 is too violent, increasing its effect.",
  [GematriaNumbersWithMeaning.Five]: "You like to talk, and you are intelligent, witty, and sharp; for this reason, you will have wide interaction with groups of people. You have strong magnetism with the opposite sex and powerful sexual appetites. Because change and freedom are so essential to you, your relationships may shift quickly. You enjoy constant activity, variety, and change, and you believe that change is progress. You are able to do anything, when and how you wish, in order to perform according to your abilities. You have a natural curiosity and are willing to take risks. Others see you as a born salesperson, publicist, or promoter. Overindulgence in social interaction and sensual pleasures can lead you to excess in food, drink, drugs/medication, or sexual contacts. You may become fickle, restless, and uncertain. You like to be among the 10 best-dressed people, or at least to be ahead of the curve in style, wearing brightly colored clothes with good taste. As a Personality number, 5 is quite favorable, as long as the other factors are not antagonistic. Personality expressed by the number 5 finds it easy to manifest its inner qualities and to adapt readily to the demands of the outer environment.",
  [GematriaNumbersWithMeaning.Six]: "You radiate a protective vibration and a strong sense of responsibility for others. People are drawn to you for advice, learning, and healing, because you have a maternal or paternal presence that conveys comfort and safety. Home seems very important to you. You are optimistic, cheerful, and reliable. You appear to love beauty and everything connected with the arts. You have a good sense of balance and symmetry; for this reason, you can see all the pieces individually and at the same time as part of a whole. Your social conscience drives you to seek truth and justice. You may become a slave to others, especially in the home, and your sense of social responsibility may degenerate into social irresponsibility or interference in other people's affairs. You are careful in choosing your clothes and show artistic talent, preserving color harmony in whatever combinations you choose. You prefer comfortable styles rather than exclusive fashions, although you are meticulous in choosing soft, harmonious fabrics. On the negative side, you may be a somewhat careless homemaker and neglectful in the way you dress. Personality number 6 gives a tendency toward luxury, great care with clothing, and concern with physical beauty. It inclines you strongly toward the opposite sex and sensual pleasures. You may often be dominated by the intensity of your passions and may have numerous unions in life.",
  [GematriaNumbersWithMeaning.Seven]: "You appear to be a loner who enjoys moments of solitude, completely removed from the crowd. Nature and regular walks in the countryside, or time spent at the beach, provide the right environment for your philosophical temperament. An air of mystery and secrecy surrounds you. You seem to be a philosopher, a mystic, a poet, a thinker, a scientist, and a researcher, whose temporary withdrawals from the world are occasions for further meditation. A sharp power of observation helps you mentally analyze any situation. You show an aristocratic air, personal dignity, and refined behavior, seeming to have an unshakable faith in the future. When you get involved in materialism, you find only disappointment, lose your composure, and become frustrated, sad, and withdrawn. Confusion, fear, and pessimism then take hold of you. You are neat, well put-together, and inclined to wear pastel or dark colors. You avoid light or bright colors and dress with good taste. When you become discontented, you grow indifferent to your appearance, neglecting so-called trivial details of color, harmony, and combination. Personality number 7 gives very attractive qualities and the ability to win much sympathy in social life. However, if moral development is not great, there will be a tendency to abuse these qualities.",
  [GematriaNumbersWithMeaning.Eight]: "You have a dynamic personality, and people recognize your authority because you appear affluent and self-controlled. There is an executive air about you, capable of directing large enterprises and business affairs. You radiate power and personal strength that commands recognition wherever you go. You seem authoritative, impartial, and ethical, and you appear to possess an inexhaustible source of strength and physical endurance. Your personal power may lead you into situations where you are tempted to abuse that power. Materialism can override your higher judgment, and you may become negative and cruel when provoked. A successful appearance is your standard; hence your insistence on well-made, high-quality clothing. You would never choose cheap items. Taken to extremes, you become flamboyant, wasteful, or a show-off, seeking to impress others through brightly colored clothes and the display of large amounts of money. A woman with this vibration may flaunt excessive jewelry and wear expensive clothes, even if bought on sale. As a Personality number, 8 is not very favorable, as it gives a coarse, imperious, and demanding disposition. Under this influence, a person easily becomes disliked because of their manner and appearance.",
  [GematriaNumbersWithMeaning.Nine]: "You seem to possess a broad range of understanding, as well as a personal magnetism that is universal in scope. Your cordial, friendly, and charming manner pleases everyone you come into contact with, and the selflessness that emanates from you makes you loved by many. You show tolerance and compassion for others, which allows you to forgive and forget easily. You are generous toward those in need and show genuine humanitarian concern. Others see you as romantic and emotional, an idealist who believes that the progress of the world justifies personal sacrifice. Sentimentality can take hold of you, and then you become susceptible to every sad story you hear. At that point you scatter your energies and emotions, and as a consequence you may become bitter. You dress in an artistic way, with a touch of drama, while still wanting your clothes to be well-fitted and comfortable. You tend to be good-looking, both in face and figure; and if you take care of your skin and maintain good posture, you may look young for a long time. As a Personality number, 9 has more or less the same meaning as it has in Individuality, with the distinction that here it is more material and somewhat coarser in its expression.",
  [GematriaNumbersWithMeaning.Eleven]: "You inspire others, leading them to see in you refinement and an artistic genius capable of moving souls. Avant-garde art is your favorite; you seem to synthesize unusual and innovative techniques. Recognition and fame may be granted to you through artistic or humanitarian efforts. You appear to be a visionary who believes in equal opportunities for all, regardless of sex, race, creed, or color. Your idealism can degenerate into egocentrism, in which case your many talents are wasted or left unused. Your mind then seeks harmful outlets for your genius, which may bring you notoriety. Your eyes shine with a spiritual light that can inspire others to reach their own potential when they witness what you have created. Your clothing style is original, and you may even design your own own models, as you have the artistic talent for it and prefer to be different.",
  [GematriaNumbersWithMeaning.TwentyTwo]: "You appear to be the masterful, diplomatic type, capable of handling all situations in a practical and efficient way. You seem to have control over the material world and the ability to bring about profound changes that could alter the course of history. You are a powerhouse who readily releases funds for charitable purposes and for organizations that benefit large groups of people. Your power can reach an international level, and you are meant to perform material services for the world. The unprecedented strength placed in your hands can eventually make you thirsty for power and, instead of serving others, you may come to exploit them out of greed. You then become indifferent to the needs of those around you and may be capable of dishonest acts to achieve your aims. You are usually careful with your clothing, choosing high-quality fabrics and conservative styles. Clothes fit you as if they were made especially for you. You wear your clothes; they do not wear you.",
  [GematriaNumbersWithMeaning.ThirtyThree]: "You impress others by your modesty, humility, and charity. You always seem to be drawn to places where your presence is needed and where you give more than you receive. Generous in all circumstances, you do not look for rewards; you appear to be a natural giver. You love children and animals and express kindness and tenderness toward them. People feel they can tell you their problems and that you will understand. Your sensitivity to the suffering of others tends to lead you into futile self-sacrifice, devoting yourself to people who often have no real intention of improving. In such cases, your martyrdom is useless, falling on barren ground. You dress in dignified styles, choosing your clothes with great care. Your manners are refined.",
  [GematriaNumbersWithMeaning.FortyFour]: "You have a disciplined, almost military bearing, walking upright with your shoulders back. This inspires confidence in you wherever you go. You seem to know where you are going, what you are going to do, and how you are going to do it. There is a practical, down-to-earth quality about you, and this reassures others. They feel that your common sense can solve their everyday problems and bring order into their material world. In time, you may become so focused on worldly problems that you bog yourself down in heavy work and burdensome responsibilities. You then lose sight of the source from which you came, and at that point your spiritual progress suffers. You like to wear military-style clothing and often buy tailored garments. You may add a military touch with braids, sashes, or distinctive buttons in order to make an impression.",
}

export const SYNTHESIS_NUMBER_MEANINGS: Record<GematriaNumbersWithMeaning, string> = {
  [GematriaNumbersWithMeaning.One]: "It is the true I AM. You are aware of yourself as the center of the world, concerned with your own desires and seeking self-preservation above all. You use your resources for your own pleasure and have little interest in the needs of others. You are in this incarnation to develop the Self, but you must not allow this to be carried to the extreme of self-love. Leadership is your key word, and you need to accept the challenge of leading while others follow you. You have independent initiative that helps you succeed through the determination to stand by your beliefs, even under pressure. You show self-confidence and the ability to win, which will make you successful under all circumstances. In the Synthesis, the number 1 is generally beneficial and favorable to triumph. It promises high social positions and success in politics and governmental occupations. The person finds a social environment favorable to their advancement, has many friends, and enjoys great prestige in the circle in which they live.",
  [GematriaNumbersWithMeaning.Two]: "Desire for peace places you in the role of peacemaker. Your destiny could lead you to act as an ambassador of goodwill in foreign nations, thus bringing countless benefits to humanity. You must use your innate tact and discipline to deal with life's difficult situations. You have a keen sense of opposites, which allows you to develop your talents along creative lines. By expanding this awareness, you not only maximize your artistic potential, but also strengthen your abilities as a mediator and a helpful companion. You tend to become an integral part of any organization or group to which you belong. In the Synthesis, this number indicates little capacity for accomplishment and results of small importance in your undertakings.",
  [GematriaNumbersWithMeaning.Three]: "Talents that allow you to choose occupations or pastimes where you can inspire others and help them rise in life. You should play a leading role and develop your gift for expression and communication through drama or foreign languages. You should explore the arts and study the religions of the world, since this gives a constructive outlet for your energies and you have a natural inclination toward spiritual philosophies. Your occupation could include therapy and the treatment of others, as well as ongoing self-improvement. To be successful, you must use your time intelligently, not wasting your energies in too many directions at once and thus delaying the fulfillment of a valuable destiny. You should promote friendship among your peers by being a true friend when called upon. You spread joy and light through your talent for self-expression. You should keep optimism as your personal trademark. In the Synthesis, the number 3 is always a good sign and promises social progress, success in undertakings, and the achievement of wide-ranging ambitions. A person under this influence has great moral stature, a pleasant character, a sociable nature, and an interest in philanthropic movements.",
  [GematriaNumbersWithMeaning.Four]: "Need to see what you've built. Well organized in your thoughts, you can run your enterprise efficiently. You convey an air of stability and, as a result, others will trust you to get the job done in an efficient and proper way. You handle money well and, because of this, may see the financial world as fertile ground for your talents. Your key words are impatience, honesty, determination, and reliability. You demand obedience and practice self-denial in order to fulfill your duties, whether real or imagined. With a sharp sense of values, you dislike mediocrity and know that anything worth having is worth waiting for. Number 4 in the Synthesis is truly favorable only when it results from 1 and 3, for in this case both the individual character and the personality are strong and harmonize with the outer vibrations of the 4. A person with this combination will have great energy, capacity for achievement, and social qualities. When formed from numbers 4 and 9 in Individuality and Personality, 4 in the Synthesis is too violent and impulsive to produce good results. It can, however, be favorable for great explorers, military leaders, and all those who devote themselves to tasks that demand exceptional physical and moral energy.",
  [GematriaNumbersWithMeaning.Five]: "Many changes occur in your life, and your mission could well be to promote progress through your willingness to accept change. You are definitely not tied to old patterns, outdated ideas, or rigidly established principles. You are ready to accept new concepts and other points of view, and you claim the freedom to suggest new ways of doing things. You have the ability to present new ideas in logical, acceptable terms. You turn changes into springboards and intelligently transform them into growth experiences. However, you do not forget conventions, for in truth you are not a rebel; you simply have the courage to leave the old behind and try the new. You are quite fluent and expressive with words and may find that writing, teaching, or selling are perfect outlets for these talents. In the Synthesis, number 5, when it is the expression of 5 and 9 or 6 and 8, is not favorable, as it brings many troubles through lack of reflection, producing restrictions and numerous obstacles. In other cases, this number is more or less beneficial and depends on the individual's moral development.",
  [GematriaNumbersWithMeaning.Six]: "You love home and family life. You are the marital type, with family as your main focus. Morally good, respectable, reliable, and generous, you enjoy comfort and the pleasures of life. Very sociable and a good host, you communicate with everyone at a social gathering. Proud of your possessions, you like to show them and to display your family's talents and achievements. You need to train your artistic talents so that you can share your sense of beauty and appreciation of the aesthetic with others. This is a vibration of artists who work by fully expressing their deep and constant love for others through their own creations. In the Synthesis, it gives a philanthropic nature and brings success through the opposite sex. It is an excellent vibration for popularity and social success, but it does not favor the financial side very much, as money is easily spent on pleasures, entertainments, and so on.",
  [GematriaNumbersWithMeaning.Seven]: "You physically separate truth from falsehood and can discover and reveal some of life’s mysteries to a waiting world. You should become anything whose field is the mind (a thinker, for example). People may consider you strange and hard to understand, but they will follow your teachings and seek your advice when they are in difficulties. Your example and public image can benefit the whole community and, eventually, the world. You find strength in solitude and wisdom in moments of silence, as well as strength in your own knowledge. You should develop your mental powers. Number 7 is rarely favorable in the Synthesis, for it is beneficial only to those who have high aspirations and a well-developed moral character. In such cases, it brings extraordinary success and great popularity.",
  [GematriaNumbersWithMeaning.Eight]: "Possessing magnificent courage and strength, you will reach your goals through effort. Recognition, success, and wealth are your rightful destiny. Perseverance in your career and long hours of intensive work, supported by ambition, lead you to the highest executive position in your chosen field. No lesser position will satisfy you. You need to unite your material strength with the spiritual and achieve self-mastery before you can attain and maintain the position you envision as the work of your life. Even if you choose the field of athletics, there is a tendency to end your life in the world of commerce. In the Synthesis, number 8 indicates that a person fulfills their aspirations through energy and authority. You can rise to high positions because of your ambition and ability, but if the Individuality and Personality numbers are not strong and favorable, you will suffer loss of position. The number 8 is always a sign of elevation, but it almost always brings loss of status through excessive ambition.",
  [GematriaNumbersWithMeaning.Nine]: "Perfection is your goal, even though you rarely attain it. Your mission is charity. You have a tendency to face many tests and adversities, but the lesson of forgiveness will bring moderation to these situations. The more you evolve, the more trials you will be able to face; therefore, take care not to lose your balance. You strive to live an ideal life, hoping to inspire others to do the same. Wanting to improve the world through philosophy and philanthropy, you become impatient when results are slow to appear. You need to realize that evolution takes place only over long cycles of time. Your breadth of thought impresses others. You must learn not to cling to old relationships. You should not remain limited to a small group, since your broad philosophy is meant to touch and clarify the lives of many. In the Synthesis, the number 9 denotes people of great physical activity – explorers, aviators, and captains of industry. It is a number of physical expansion, military activity, and authority. When the other numbers are in harmony, there is the possibility of great triumphs.",
  [GematriaNumbersWithMeaning.Eleven]: "You may become a leader in public or civil affairs in your community and help provide a better standard of living for the less fortunate. Your career aspirations could express themselves on stage or screen, as a preacher, or as a dynamic teacher. Your standard of conduct should be higher than average. In some way, you are meant to attain fame or recognition, and since this vibration confers great creative potential, the arts or inventive professions are your most likely and favorable choices. You have the ability to unstop the creative source and to infuse your work with an inspired touch that will affect the souls of all who come into contact with what you create.",
  [GematriaNumbersWithMeaning.TwentyTwo]: "You trust in your leadership ability and therefore naturally take on great responsibilities. This fulfills your longing for important achievements. Once you have assumed a position of great power and fortune, you will want to take part in new mass movements and major civic and community projects. You are a super-materialist whose influence can become worldwide. On the material plane you are a builder; you create on a grand scale. Bridges, hospitals, museums, and other such structures are the kind of works you tend to leave to the world – works that help and enlighten humanity. Because your influence reaches so far, you must guard carefully against motives that run contrary to ethics, for in time they will affect many lives. Serve well, and you will be rewarded in direct proportion.",
  [GematriaNumbersWithMeaning.ThirtyThree]: "You tend toward self-sacrifice and service to others. There is a tendency to crucify your emotions and to suffer the pains of the world. Your actions are tempered by compassion, grounded in your understanding of right and justice. You often notice that you must live impersonally, with a detached yet protective attitude, and you recognize that the way you handle the burdens placed upon you is a supreme example for others. People sense your understanding nature and are naturally drawn to you in search of comfort and help. By responding to the needs of others, you will find the fulfillment that this master number demands of you. If you do not live in accordance with this master number, you may live as a 6 instead. In that case, you will develop a martyr complex and receive little recognition for your sacrifices.",
  [GematriaNumbersWithMeaning.FortyFour]: "This vibration demands great discipline and perseverance, and the ability to make the best of any situation that arises. You are quite resourceful, drawing on your strong reserves of common sense and logic to solve whatever problems appear. Your destiny is to serve the material needs of the world through productive, wholesome methods. You are meant to gain complete mastery over your mind and body while on Earth. Your desire should be that others share in universal prosperity, and you must establish conditions in which this becomes possible. You seek to improve the world in its physical aspect.",
}